# Model arguments
model_name_or_path: "Columbia-NLP/LION-LLaMA-3-8b-dpo-v1.0"
ref_model_name_or_path: null # use model_name_or_path if null
torch_dtype: "bfloat16"
use_flash_attention_2: true

# Data training arguments
# will be overwritten with online data in the example/*/odpo.sh scripts
train_dataset_mixer:
  Columbia-NLP/DPO-UltraFeedback_binarized: 1.0
train_dataset_splits: "train_prefs"

eval_dataset_mixer:
  Columbia-NLP/DPO-UltraFeedback_binarized: 1.0
eval_dataset_splits: "test_prefs"

preprocessing_num_workers: 64
shuffle_train_dataloader: true
use_fast_model: false
mask_embed_grad: false
dataset_cache_dir: "dataset_cache"

# DPOTrainer arguments
bf16: true
tf32: true
beta: 0.01
do_eval: true
evaluation_strategy: "no"
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
learning_rate: 5.0e-07
log_level: "info"
logging_steps: 10
lr_scheduler_type: "linear"
max_length: 2048
max_prompt_length: 512
num_train_epochs: 1
optim: "adamw_torch"
output_dir: "model_checkpoints/LION-LLaMA-3-8b-odpo-v1.0"
gradient_accumulation_steps: 16
per_device_train_batch_size: 2
per_device_eval_batch_size: 2
save_strategy: "epoch"
save_total_limit: 1
seed: 42
warmup_ratio: 0.1
report_to:
  - wandb

# wandb logging config
wandb_project: "LIONs"
wandb_group: "lion-llama-3-v1.0"
