# Model arguments
model_name_or_path: "Columbia-NLP/LION-Gemma-2b-sft-v1.0"
ref_model_name_or_path: null # use model_name_or_path if null
torch_dtype: "bfloat16"
use_flash_attention_2: true

# Data training arguments
train_dataset_mixer:
  Columbia-NLP/DPO-distilabel-capybara-dpo-7k-binarized: 1.0
  Columbia-NLP/DPO-distilabel-intel-orca-dpo-pairs_cleaned: 1.0
  Columbia-NLP/DPO-UltraFeedback_binarized: 1.0
  Columbia-NLP/DPO-py-dpo-v0.1: 1.0
  Columbia-NLP/DPO-tldr-summarisation-preferences: 0.1
  Columbia-NLP/DPO-HelpSteer: 1.0
  Columbia-NLP/DPO-PKU-SafeRLHF: 0.1
  Columbia-NLP/DPO-Nectar: 0.25
train_dataset_splits:
  Columbia-NLP/DPO-distilabel-capybara-dpo-7k-binarized: "train"
  Columbia-NLP/DPO-distilabel-intel-orca-dpo-pairs_cleaned: "train"
  Columbia-NLP/DPO-UltraFeedback_binarized: "train_prefs"
  Columbia-NLP/DPO-py-dpo-v0.1: "train"
  Columbia-NLP/DPO-tldr-summarisation-preferences: "train"
  Columbia-NLP/DPO-HelpSteer: "train"
  Columbia-NLP/DPO-PKU-SafeRLHF: "train"
  Columbia-NLP/DPO-Nectar: "train"

eval_dataset_mixer:
  Columbia-NLP/DPO-UltraFeedback_binarized: 1.0
eval_dataset_splits:
  Columbia-NLP/DPO-UltraFeedback_binarized: "test_prefs"

preprocessing_num_workers: 64
shuffle_train_dataloader: true
use_fast_model: false
mask_embed_grad: false
dataset_cache_dir: "dataset_cache"

# DPOTrainer arguments
bf16: true
tf32: true
beta: 0.05
do_eval: true
evaluation_strategy: "no"
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
learning_rate: 5.0e-07
log_level: "info"
logging_steps: 10
lr_scheduler_type: "linear"
max_length: 2048
max_prompt_length: 512
num_train_epochs: 2
optim: "adamw_torch"
output_dir: "model_checkpoints/LION-Gemma-2b-dpo-v1.0"
gradient_accumulation_steps: 32
per_device_train_batch_size: 1
per_device_eval_batch_size: 1
save_strategy: "epoch"
save_total_limit: 1
seed: 42
warmup_ratio: 0.1
report_to:
  - wandb

# wandb logging config
wandb_project: "LIONs"
wandb_group: "lion-gemma-v1.0"
