# Model arguments
model_name_or_path: alignment-handbook/zephyr-7b-sft-full
model_revision: main
torch_dtype: bfloat16
use_flash_attention_2: true

# Data training arguments
chat_template: "{% for message in messages %}\n{% if message['role'] == 'user' %}\n{{ '<|user|>\n' + message['content'] + eos_token }}\n{% elif message['role'] == 'system' %}\n{{ '<|system|>\n' + message['content'] + eos_token }}\n{% elif message['role'] == 'assistant' %}\n{{ '<|assistant|>\n'  + message['content'] + eos_token }}\n{% endif %}\n{% if loop.last and add_generation_prompt %}\n{{ '<|assistant|>' }}\n{% endif %}\n{% endfor %}"
# all train_ splits will be mixed, subsampled, and used for training,
# and all test_ splits will be mixed and used for evaluation
# to make sure all dsets have the same 'formatting', see src/dataloads/formatting.py
dataset_splits:
  HuggingFaceH4/ultrafeedback_binarized: ["train_sft", "test_sft"]
dataset_mixer:
  HuggingFaceH4/ultrafeedback_binarized: 1.0
preprocessing_num_workers: 12

# SFT trainer config
bf16: true
do_eval: true
gradient_accumulation_steps: 8
gradient_checkpointing: true
# gradient_checkpointing_kwargs:
#   use_reentrant: False
learning_rate: 2.0e-05
log_level: info
logging_steps: 5
logging_strategy: steps
lr_scheduler_type: cosine
max_seq_length: 2048
max_steps: -1
num_train_epochs: 1
output_dir: model_checkpoints/zephyr-7b-sft-2-reprod
overwrite_output_dir: true
per_device_eval_batch_size: 4
per_device_train_batch_size: 4
push_to_hub: false
remove_unused_columns: true
report_to:
- wandb
save_strategy: "epoch"
# save_steps: 50
save_total_limit: 1
# metric_for_best_model: "eval_loss"
# load_best_model_at_end: true
evaluation_strategy: "steps"
eval_steps: 50
seed: 42
warmup_ratio: 0.1

## wandb logging config
wandb_project: "when2rl"
wandb_group: "zephyr-sft-2-reprod"