# Model arguments
model_name_or_path: Columbia-NLP/gemma-2b-lion-sft-v0.1
ref_model_name_or_path: null # use model_name_or_path if null
torch_dtype: bfloat16
use_flash_attention_2: true

# Data training arguments
dataset_splits:
  # when2rl/dpo-mix-7k-rescaled_reformatted: ["train", "test"]
  # when2rl/UltraFeedback_binarized_cleaned_annotated: ["train_prefs", "test_prefs"]
  # when2rl/distilabel-capybara-dpo-7k-binarized_reformatted: ["train"]
  # when2rl/distilabel-intel-orca-dpo-pairs_cleaned_reformatted: ["train"]
  when2rl/OpenHermesPreferences_reformatted: ["train"]
  # when2rl/OpenHermesPreferences_reasoning: ["train"]
  # when2rl/OpenHermesPreferences_knowledge: ["train"]
  # when2rl/gutenberg-dpo-v0.1_reformatted: ["train"]
  # when2rl/py-dpo-v0.1_reformatted: ["train"]
  # when2rl/truthy-dpo-v0.1_reformatted: ["train"]
  # when2rl/prm_dpo_pairs_cleaned_reformatted: ["train"]
  when2rl/dpo-mix-7k-rescaled_reformatted: ["test"]
dataset_mixer:
  when2rl/dpo-mix-7k-rescaled_reformatted: 1.0
  # when2rl/UltraFeedback_binarized_cleaned_annotated: 0.5
  # when2rl/distilabel-capybara-dpo-7k-binarized_reformatted: 0.5
  # when2rl/distilabel-intel-orca-dpo-pairs_cleaned_reformatted: 0.3
  when2rl/OpenHermesPreferences_reformatted: 1.0
  # when2rl/OpenHermesPreferences_reasoning: 0.1
  # when2rl/OpenHermesPreferences_knowledge: 1.0
  # when2rl/gutenberg-dpo-v0.1_reformatted: 1.0
  # when2rl/py-dpo-v0.1_reformatted: 0.2
  # when2rl/truthy-dpo-v0.1_reformatted: 1.0
  # when2rl/prm_dpo_pairs_cleaned_reformatted: 0.3
preprocessing_num_workers: 64
max_data_size: -1  # -1 means all data

# DPOTrainer arguments
bf16: true
tf32: true
beta: 0.1
do_eval: true
evaluation_strategy: "epoch"
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: False
learning_rate: 5.0e-07
log_level: info
logging_steps: 10
lr_scheduler_type: linear
max_length: 2048
max_prompt_length: 512
num_train_epochs: 6
optim: adamw_torch
output_dir: model_checkpoints/gemma-2b-zephyr-dpo-v0.4
gradient_accumulation_steps: 32
per_device_train_batch_size: 1
save_strategy: "epoch"
save_total_limit: 1
seed: 42
warmup_ratio: 0.1
report_to:
- wandb

## wandb logging config
wandb_project: "when2rl"
wandb_group: "zephyr-gemma-2b-scaling"