# Model arguments
model_name_or_path: model_checkpoints/LION-LLaMA-3-8b-sft-v1.0
model_revision: main
torch_dtype: bfloat16

# Data arguments
train_dataset_mixer:
  Columbia-NLP/DPO-distilabel-capybara-dpo-7k-binarized: 1.0
  Columbia-NLP/DPO-distilabel-intel-orca-dpo-pairs_cleaned: 1.0
  Columbia-NLP/DPO-UltraFeedback_binarized: 1.0
  Columbia-NLP/DPO-py-dpo-v0.1: 1.0
  Columbia-NLP/DPO-HelpSteer: 1.0
  Columbia-NLP/DPO-Nectar: 1.0
  Columbia-NLP/DPO-PKU-SafeRLHF: 0.1  # include 10k examples to balance ratio
train_dataset_splits:
  Columbia-NLP/DPO-distilabel-capybara-dpo-7k-binarized: "train"
  Columbia-NLP/DPO-distilabel-intel-orca-dpo-pairs_cleaned: "train"
  Columbia-NLP/DPO-UltraFeedback_binarized: "train_prefs"
  Columbia-NLP/DPO-py-dpo-v0.1: "train"
  Columbia-NLP/DPO-HelpSteer: "train"
  Columbia-NLP/DPO-Nectar: "train"
  Columbia-NLP/DPO-PKU-SafeRLHF: "train"

preprocessing_num_workers: 64
shuffle_train_dataloader: true
use_fast_model: true
dataset_cache_dir: dataset_cache

# DPOTrainer arguments
beta: 0.01
learning_rate: 5.0e-7
bf16: true
tf32: true
do_eval: false
evaluation_strategy: "no"
eval_steps: 100
gradient_accumulation_steps: 16
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: False
log_level: info
logging_steps: 5
lr_scheduler_type: cosine
max_length: 2048
max_prompt_length: 1024
num_train_epochs: 1
optim: adamw_torch
output_dir: model_checkpoints/LION-LLaMA-3-8b-dpo-v1.0
per_device_train_batch_size: 2
per_device_eval_batch_size: 4
report_to:
- wandb
save_strategy: "steps"
save_steps: 100
save_total_limit: 2
seed: 27
warmup_ratio: 0.1