dataset_to_test:
  # HuggingFaceH4/ultrafeedback_binarized: train_prefs
  when2rl/UltraFeedback_binarized_cleaned_annotated: train_prefs
  HuggingFaceH4/ultrachat_200k: train_sft
# a dict for each dataset
filtering:
  when2rl/UltraFeedback_binarized_cleaned_annotated:
    # source: evol_instruct,ultrachat,sharegpt
    # language: en
  HuggingFaceH4/ultrachat_200k:
    # language: en
per_dataset_size:
  train: 1000
  validation: 500
  test: 500
content_to_predict: prompt
save_strategy: 'no'