chat_template: "{% for message in messages %}\n{% if message['role'] == 'user' %}\n{{ '<|user|>\n' + message['content'] + eos_token }}\n{% elif message['role'] == 'system' %}\n{{ '<|system|>\n' + message['content'] + eos_token }}\n{% elif message['role'] == 'assistant' %}\n{{ '<|assistant|>\n'  + message['content'] + eos_token }}\n{% endif %}\n{% if loop.last and add_generation_prompt %}\n{{ '<|assistant|>' }}\n{% endif %}\n{% endfor %}"
dataset_to_test:
  # HuggingFaceH4/ultrafeedback_binarized: train_prefs
  when2rl/UltraFeedback_binarized_cleaned_annotated: train_prefs
# a dict for each dataset
fullid_files:
  data/analysis/ultrafbk/rm-importance-ge0.9_v_score-diff-ge3_confidence/rm-importance-only_train_data_ids.csv: rm-importance
  data/analysis/ultrafbk/rm-importance-ge0.9_v_score-diff-ge3_confidence/score-diff-only_train_data_ids.csv: score-diff
per_dataset_size:
  train: 1000
  validation: 500
  test: 500
content_to_predict: prompt
save_strategy: 'no'