# Model arguments
model_name_or_path: stabilityai/stablelm-2-1_6b
torch_dtype: bfloat16
trust_remote_code: true
model_revision: 39d1453f64ffe2a97df9b2f1e6d007eb28248245
use_flash_attention_2: true

# Data training arguments
chat_template: "{% for message in messages %}\n{% if message['role'] == 'user' %}\n{{ '<|user|>\n' + message['content'] + eos_token }}\n{% elif message['role'] == 'system' %}\n{{ '<|system|>\n' + message['content'] + eos_token }}\n{% elif message['role'] == 'assistant' %}\n{{ '<|assistant|>\n'  + message['content'] + eos_token }}\n{% endif %}\n{% if loop.last and add_generation_prompt %}\n{{ '<|assistant|>' }}\n{% endif %}\n{% endfor %}"
dataset_splits:
  HuggingFaceH4/ultrachat_200k: ["train_sft", "test_sft"]
dataset_mixer:
  HuggingFaceH4/ultrachat_200k: 1.0
preprocessing_num_workers: 4

# SFT trainer config
bf16: true
do_eval: true
gradient_accumulation_steps: 8  # 8, 2
gradient_checkpointing: true
# gradient_checkpointing_kwargs:
#   use_reentrant: true
learning_rate: 5.0e-05  # 5e-5, 2e-5
log_level: info
logging_steps: 5
logging_strategy: steps
lr_scheduler_type: cosine
max_seq_length: 2048
max_steps: -1
num_train_epochs: 3
output_dir: model_checkpoints/stablelm-sft-full_bsz128_lr5e-5
evaluation_strategy: epoch
save_strategy: epoch
# save_strategy: "steps"
# save_steps: 500
save_total_limit: 1
overwrite_output_dir: true
per_device_eval_batch_size: 4
per_device_train_batch_size: 16
push_to_hub: false
remove_unused_columns: true
report_to:
- wandb
seed: 42
warmup_ratio: 0.1

## wandb logging config
wandb_project: "when2rl"
wandb_group: "stablelm-sft-full"