# Model arguments
model_name_or_path: Columbia-NLP/gemma-2b-zephyr-sft
torch_dtype: bfloat16
use_flash_attention_2: true

# Data training arguments
dataset_splits:
  argilla/dpo-mix-7k: ["train", "test"]
  # when2rl/UltraFeedback_binarized_cleaned_annotated: ["train_prefs", "test_prefs"]
dataset_mixer:
  argilla/dpo-mix-7k: 1.0
  # when2rl/UltraFeedback_binarized_cleaned_annotated: 1.0
id_file_path: data/deita/ultrafbk_deita.csv
preprocessing_num_workers: 64

# DPOTrainer arguments
bf16: true
tf32: true
beta: 0.1
do_eval: true
evaluation_strategy: "epoch"
gradient_accumulation_steps: 8
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: False
learning_rate: 5.0e-07
log_level: info
logging_steps: 10
lr_scheduler_type: linear
max_length: 2048
max_prompt_length: 512
num_train_epochs: 6
optim: adamw_torch
output_dir: model_checkpoints/gemma-2b-dpo-ultrabkf-deita-v0.1
per_device_train_batch_size: 2
save_strategy: "epoch"
save_total_limit: 1
seed: 42
warmup_ratio: 0.1
report_to:
- wandb

## wandb logging config
wandb_project: "when2rl"
wandb_group: "zephyr-gemma-2b"